[package]
name = "swinstall_stack"
version = "0.1.0"
authors = ["jonathan gerber <jlgerber@gmail.com>"]
edition = "2018"

[[bin]]
name="swinst"
path="src/bin/main.rs"

[dependencies]
quick-xml = "0.13.1"
chrono = "0.4.6"
failure = "0.1.3"
env_logger = "0.6.0"
log = "0.4.6"
structopt = "0.2.14"
